version: 2

always_pending:
  title_regex: '(WIP|wip)'  
  labels:
    - wip
  explanation: 'This PR is a work in progress...'

group_defaults:
  reset_on_push:
    enabled: true
  reject_value: -1
  approve_by_comment:
    enabled: true
    approve_regex: '^(Approved|:shipit:|:\+1:|Engage)'

groups:
  development:
    author_approval:
      auto: true
    conditions:
      branches:
        - development
    required: 2
    users:
      - brantje
      - dschaper
      - jacobsalmela
      - Mcat12
      - PromoFaux
  
  development-master:
    conditions:
      branches:
        - "master...development" # Only needed if merging into master from development
    required: 1
    users:
      - brantje
      - dschaper
      - jacobsalmela
      - Mcat12
      - PromoFaux
