name: Pull Requests

on:
  pull_request_target: # By default, a workflow only runs when a pull_request_target's activity type is opened, synchronize, or reopened.
    branches:
      - master # Run only on master branch

jobs:
  base_branch_check:
    runs-on: ubuntu-latest
    name: Base Branch Check
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: >
            Thank you very much for your contribution. An automated check has shown that you have opened your Pull Request to the `master` branch. As our project uses this branch for released code we ask you to submit any Pull Requests to the `development` branch instead. Note that, in most cases, you don't have to create a new pull request but can simply [change the base branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request). After changing the base branch, ensure your branch does not contain any extra commits that aren't from you. If this is the case, please [rebase](https://anavarre.net/how-to-rebase-a-github-pull-request/) your branch.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
