name: Mark stale issues

on:
  schedule:
  - cron: '30 * * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        debug-only: true
        days-before-stale: 30
        days-before-close: 5
        stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Please comment or update this issue or it will be closed in 5 days.'
        stale-issue-label: 'Submitter Attention Required'
        exempt-issue-labels: 'pinned, Fixed in next release, Bug: Confirmed'
        exempt-all-issue-assignees: true
